.builds/alpine.yml: check patches for sign-off

diff --git a/.builds/alpine.yml b/.builds/alpine.yml
--- a/.builds/alpine.yml
+++ b/.builds/alpine.yml
@@ -5,6 +5,16 @@ sources:
 - https://git.sr.ht/~sircmpwn/harec
 - https://git.sr.ht/~sircmpwn/hare
 tasks:
+- signoff: |
+    cd hare
+    if [ "$BUILD_REASON" = "patchset" ]
+    then
+        if ! git log --format='%b' origin/master^^.. | grep 'Signed-off-by' >/dev/null
+        then
+            echo "Patch missing Signed-off-by"
+            exit 1
+        fi
+    fi
 - qbe: |
     cd qbe
     make PREFIX=/usr
